apiVersion: operator.ibm.com/v1alpha1
kind: AuditLogging
metadata:
  name: example-auditlogging
  labels:
    app.kubernetes.io/instance: "common-audit-logging"
    app.kubernetes.io/managed-by: "ibm-auditlogging-operator"
    app.kubernetes.io/name: "common-audit-logging"
spec:
  fluentd:
    enabled: false
    imageRegistry: quay.io/opencloudio/
    pullPolicy: IfNotPresent
    journalPath: /run/log/journal
    clusterIssuer: cs-ca-clusterissuer
  policyController:
    imageRegistry: quay.io/opencloudio/
    pullPolicy: IfNotPresent
    verbosity: "0"
    frequency: "10"
